### PR TITLE
Add a commandline and linux compatible version

### PR DESCRIPTION
**Pull request by ghost**
^ see above

btw am am running currently the project on my server. 

Here are the live versions of this project
(it refreshes every minute)

Running this commit
b1194e1a84d7704896156be182f4da62f79cea2e

http://delaiyoid.de/creatures.dat
http://delaiyoid.de/tilemap.dat

### CODE REVIEW

**Comment by pampersrocker** [comment]
Hey, we got a little bit distracted with other projects, I've merged your changes, but changed some stuff:
9be9634da4fd1eac5893cfc566e7bfcde723536e Fixed some compiler warnings and removed unessecary references.
The following one is odd, the code in your merge request ist just an empty loop, which does not run any simulation, I've changed this in the following commit:
1764349d3ad252331863bb0b28b641868729ace1

**Comment by ghost** [comment]
yeah, I noticed that it isn't working, but I couldn't find out why :/

**Comment by ghost** [comment]
ow well I see now .-.

**Comment by ghost** [comment]
#sleepy programming after 2 am is a bad idea

**Pull request merged**
